---
title: "Publication"
---


[ORCID](orcid.org/0000-0003-3165-3218)


## Research article

[6] **Richard, M.**, Chuffart, F, Duplus-Bottin, H., Pouyet, F., Spichty, M., Fulcrand, E., Entrevan, M., Barthelaix, A., Springer, M., Jost, D., and G. Yvert , G. (2017). Assigning function to natural allelic variation via dynamic modeling of gene network induction. bioRxiv 140467. [Click](https://doi.org/10.1101/140467) or [PDF](140467.full.pdf)

[5] Salignon #, J., **Richard #, M.**, Fulcrand, E., & Yvert, G. (2017) Unexpected selection in fluctuating environments. bioRxiv 129163. [Click](https://doi.org/10.1101/129163) or [PDF](129163.full.pdf)

[4] Chuffart, F., **Richard, M.**, Jost, D., Burny, C., Duplus-Bottin, H., Ohya, Y., & Yvert, G. (2016). Exploiting Single-Cell Quantitative Data to Map Genetic Variants Having Probabilistic Effects. PLoS Genetics, 12(8), e1006213. [Click](http://doi.org/10.1371/journal.pgen.1006213) or [PDF](PLoS Genetics 2016 Chuffart.pdf)

[3] **Richard, M.** & Yvert, G. L. How does evolution tune biological noise? Front. Genet. 5, 1011 (2014). [Click](http://doi.org/10.3389/fgene.2014.00374) or [PDF](frontiers.pdf)

[2] **Richard, M.**, Boulin, T., Robert, V. J. P., Richmond, J. E., & Bessereau, J.-L. (2013). Biosynthesis of ionotropic acetylcholine receptors requires the evolutionarily conserved ER membrane complex. Proceedings of the National Academy of Sciences of the United States of America, 110(11), E1055–63. [Click](http://doi.org/10.1073/pnas.1216154110) or [PDF](pnas.pdf)

[1] Legent, K., Steinhauer, J., **Richard, M.**, & Treisman, J. E. (2012). A screen for X-linked mutations affecting Drosophila photoreceptor differentiation identifies Casein kinase 1α as an essential negative regulator of wingless signaling. Genetics, 190(2), 601–616. [Click](http://doi.org/10.1534/genetics.111.133827) or [PDF](genetics.pdf)


##Communication at conferences

###2017

Epigenetics and Cancer, Poster, Heidelberg, Allemagne.
*Identifying epigenetic hotspots in lung cancer*

Advanced lecture course on computational systems biology, Talk, Aussois, France. 
*Functional Genetic Diversity of the Yeast Galactose Network*

###2016

JOBIM, Poster, Lyon, France.
*Functional Genetic Diversity of the Yeast Galactose Network*

###2015 

Design optimization and control in system and synthetic biology, Poster, Paris, France.
*Functional Genetic Diversity of the Yeast Galactose Network*

BCM Seminar, Invited speaker, Grenoble, France. 
*Functional Genetic Diversity of the Yeast Galactose Network*

JOBIM, Poster, Clermont-Ferrand.
*Identification of fitness advantage in dynamic environment by modelisation of BAR-seq data*

Quatrièmes Rencontres R, Talk, Grenoble, France.
*A general method to map single-cell probabilstic trait loci of the genome*

###2014 

Experimental Approaches to Evolution and Ecology using Yeast and other Model Systems, Poster, Heidelberg, Germany. *Genetics of fitness in dynamic environments*

Single cells genomics, Poster, Stockholm, Sweden.
*Competition between cells in dynamic environments*

###2012 

Young Researcher in Life Sciences, Talk, 3rd prize, Paris, France.

*Control of acetylcholine receptor maturation and ER homeostasis by a new transmembrane complex*

LBMC Seminar, Invited speaker, Lyon, France.

*Control of acetylcholine receptor maturation and ER homeostasis by a new transmembrane complex*

Ver midi, Talk, Paris, France.

*Control of acetylcholine receptor maturation and ER homeostasis by a new transmembrane complex*

###2011 

18th International Worm Meeting, Poster, Los Angeles, USA.

*Control of acetylcholine receptor maturation and ER homeostasis by a new transmembrane complex*

###2010 

Neuronal development, synaptic function and behaviour in C. elegans, Poster, Ma- dison, USA.

*TMEM-93 is a Conserved Transmembrane Protein Required for Assembly or Stability of Acetylcholine Receptors*

###2009 

17th International Worm Meeting, Poster, Los Angeles, USA.

*TMEM-93 is a Conserved Transmembrane Protein Required for Assembly or Stability of Acetylcholine Receptors*
